apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsu-app
  labels:
    app: devsu-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsu-app
  template:
    metadata:
      labels:
        app: devsu-app
    spec:
      containers:
        - name: devsu-app
          image: 693266754137.dkr.ecr.us-east-1.amazonaws.com/devsu:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /api/users
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: devsu-app
  labels:
    app: devsu-app
spec:
  selector:
    app: devsu-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

